### ISSUE TITLE
No chats in discord servers, and no dm messages

### ISSUE THREAD

**Issue by D3adTrace** [SebOuellette/LiveBot#257]
- Branch/Release: From arch aur, 1.3.1-1

#### Errors
LiveBot started
errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
load.js:79 Logged in as <removed by me>
load.js:80 Owned by: <removed by me>
guildList.js:21 adding guilds
2errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
load.js:431 Finished loading
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
dmList.js:62 Switching to dms
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)
3errorHandler.js:76 There is no token stored
customTokenErrors @ errorHandler.js:76
node:internal/fs/utils:347 Uncaught Error: EACCES: permission denied, open 'json/logins.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at set settings [as settings] (userSettings.js:101:12)
    at set tokenSettings [as tokenSettings] (userSettings.js:118:23)
    at set lastGuild [as lastGuild] (userSettings.js:92:28)
    at img.onclick (guildList.js:81:36)

#### Steps required to reproduce the bug
Login into bot with token

#### Screenshot
![2023-07-19_18-41](https://github.com/SebOuellette/LiveBot/assets/100424861/18ffe239-db52-46a3-b7e6-3fa11970af5c)

**Comment by D3adTrace** [comment]
> First of all, that's cool somebody put LiveBot on the aur.
> 
> Second, make sure all your gateway intents are enabled to see any servers. Even then, LiveBot can only show servers that the bot and the owner are both in. These errors are hard to read, and woupd be better in a screenshot so i have some context though. It is possible that the aur version is not functional, and you'll have to download the release yourself.

You're right, it's aur release problem
